### ISSUE TITLE
Compare performance with https://nemo157.com/roaring-rs/

### ISSUE THREAD

**Issue by lemire** [saulius/croaring-rs#6] opened 2016-08-22 20:32 UTC
There is a pure (?) Rust implementation of Roaring... it would be interesting to compare...

**Comment by saulius** [comment] 2016-08-23 06:38
Will add benchmarks over the week. From the first glance it actually seems that the Rust native version is faster, but I'm neither a benchmarking nor a Rust expert:

```
test croaring_bench_add                 ... bench:          12 ns/iter (+/- 1)
test croaring_bench_cardinality_100000  ... bench:           0 ns/iter (+/- 0)
test croaring_bench_cardinality_1000000 ... bench:          34 ns/iter (+/- 24)
test croaring_bench_contains_false      ... bench:           2 ns/iter (+/- 0)
test croaring_bench_create              ... bench:         586 ns/iter (+/- 362)
test croaring_bench_remove              ... bench:           3 ns/iter (+/- 2)
test native_bench_add                   ... bench:           8 ns/iter (+/- 3)
test native_bench_cardinality_100000    ... bench:           8 ns/iter (+/- 6)
test native_bench_cardinality_1000000   ... bench:           0 ns/iter (+/- 0)
test native_bench_contains_false        ... bench:           1 ns/iter (+/- 0)
test native_bench_create                ... bench:           2 ns/iter (+/- 0)
test native_bench_remove                ... bench:           2 ns/iter (+/- 1)
```

cc @llogiq

**Comment by lemire** [comment] 2016-08-23 14:21
@saulius 

Thanks.

I don't think it is possible for CRoaring-backed version to be an order of magnitude slower... unless the wrapper adds a *lot* of overhead.

**Comment by saulius** [comment] 2016-08-30 06:01
Hello @lemire,

So I've been doing some digging into bitmap creation case as it has the biggest difference in numbers:

```
test croaring_bench_create              ... bench:         586 ns/iter (+/- 362)
test native_bench_create                ... bench:           2 ns/iter (+/- 0)
```

I created a very simple test program in C and Rust which allocates and deallocates the bitmap, e.g.:

```c
int main() {
   int i;

   for(i = 0; i < 100000000; i++) {
      roaring_bitmap_t * bm = roaring_bitmap_create();
      roaring_bitmap_free(bm);
   }
    return 0;
}
```

Rust with [`croaring-rs`](https://github.com/saulius/croaring-rs):

```rust
extern crate croaring;

use croaring::Bitmap;

fn main() {
    for i in 1..100000000 {
        let bitmap = Bitmap::create();
    }
}
```

Rust with [`roaring-rs`](https://github.com/Nemo157/roaring-rs):

```rust
extern crate roaring;

use roaring::RoaringBitmap;

fn main() {
    for i in 1..100000000 {
        let bitmap: RoaringBitmap<u32> = RoaringBitmap::new();
    }
}
```

Rust deallocates [when a variable goes out of scope](http://pcwalton.github.io/blog/2013/03/18/an-overview-of-memory-management-in-rust/). I did profile these programs with Instruments on OSX and here are the results:

1. [CRoaring (C)](https://gist.github.com/saulius/abfd597f507ca995955e6dc30d446450) out of total runtime 56seconds `malloc` in `ra_create_with_capacity` takes 20seconds and `roaring_bitmap_free` takes quite a lot of time too. I compiled this as one of the benchmarks in CRoaring project so I hope all optimizations are enabled there.
2. [croaring-rs](https://gist.github.com/saulius/191fb4d68635b33b676fd5ba3110cfa3) there is more Rust stuff in the callstack, but there is no significant difference (if any) from `CRoaring` in runtime.
3. [croaring-rs + jemalloc](https://gist.github.com/saulius/6a8e81c3d011b8ef5ec8bf58890818e1) since it seems a lot of allocations/deallocations are happening I tried to link against [jemalloc](https://github.com/jemalloc) allocator which is used by default in Rust programs. And it apparently gives close to a 4.5x times performance boost. Same speedup if C benchmark programs is linked against jemalloc.
4. [roaring-rs](https://gist.github.com/saulius/e02781b78746faa453750f31ac57419d) an optimized version runs too fast and OSX's Instruments does not even record anything so this is a profile of unoptimized version which is still faster than my `croaring + jemalloc` attempt. Allocations/deallocations still take some time, but overall it's really fast.

So to create a bitmap `roaring-rs` actually just [allocates a bitmap struct and an empty inner vector of containers](https://github.com/Nemo157/roaring-rs/blob/5089f180ca7e17db25f5c58023f4460d973e747f/src/imp.rs#L15) and that is it. There is no preallocation for specific capacity that seem to involve [quite a lot of malloc/free](https://github.com/RoaringBitmap/CRoaring/blob/151b81670faab678670da5f105eac1f72c96b029/src/roaring_array.c#L64-L73). Commenting these allocations/deallocations seems to greatly improve `create` performance, yet, of course, it breaks functionality.

Do my findings make sense? Perhaps `roaring-rs` is loosing something for not pre-allocating memory? Yet `insert`/`add` performance seems to be faster with `roaring-rs` as well. Perhaps CRoaring should adopt slab allocation scheme in order to avoid repeated `malloc`s and `free`s? What do you think?

**Comment by lemire** [comment] 2016-08-30 23:18
I'll get back to you.

**Comment by lemire** [comment] 2016-08-31 20:44
My results do not agree with yours...

https://github.com/lemire/roaring_rust_benchmark#results

As you can see, your ``croaring`` is faster. 



On  my Mac laptop, I do reproduce "somewhat" your result...

```bash
$ cargo bench
    Finished release [optimized] target(s) in 0.0 secs
     Running target/release/deps/roaring_rust_benchmark-9a59540862f5625d

running 2 tests
test tests::croaring_create_bench ... bench:         938 ns/iter (+/- 1,061)
test tests::roaring_create_bench  ... bench:         294 ns/iter (+/- 422)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured

     Running target/release/roaring_rust_benchmark-155ad1005dd24153

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

At no point do I see "orders of magnitude" differences however. I am curious as to why your wrapper is 3x slower on my Mac. But I never use my laptop for benchmarking... as I do not trust its configuration. 

Can you go and try to reproduce my results?

**Comment by lemire** [comment] 2016-09-01 00:48
The issue, of course, is that ``malloc`` is very slow on Macs. I suspect that's why you saw such benefits from using  jemalloc.

**Comment by saulius** [comment] 2016-09-01 06:48
@lemire I tried to run this benchmark on Linux with server grade, yet oldish CPU (E5-2680) and I really can reproduce your findings:

```
test tests::croaring_create_bench ... bench:         269 ns/iter (+/- 7)
test tests::roaring_create_bench  ... bench:         339 ns/iter (+/- 13)
```

And yes, it seems that there is something wrong with `malloc` on Macs. I will spend some time to implement automated benchmarks for all methods and run these on both systems. Will post back my findings.

**Comment by saulius** [comment] 2016-09-01 06:52
I might have actually missed this bit

```
// use `test::black_box` to prevent compiler optimizations from disregarding
// unused values
```

while benchmarking - that could have been the main problem. Thanks for pointing this out!

**Comment by lemire** [comment] 2016-09-01 14:19
@saulius 

If you could post your full benchmarking code, that'd be sweet.  (Or you can issue PRs to https://github.com/lemire/roaring_rust_benchmark)

I have done some microbenchmarking and it looks like ``malloc`` is about ten times as expensive on my Mac as it is on a Linux box. I think that this calls for a fix in ``CRoaring``, something I am investigating right now.

**Comment by lemire** [comment] 2016-09-03 01:39
Please see this PR: https://github.com/saulius/croaring-rs/pull/7 I expect you will see some performance gains. Mostly, I trimmed the number of ``malloc`` calls. It is not huge, but it is measurable. I expect that gains on Macs are going to be even larger.

If you merge the PR, it would be interesting to have an updated performance comparison with https://nemo157.com/roaring-rs/

**Comment by saulius** [comment] 2016-09-03 12:45
@lemire the fix seems to be working great and greatly improves performance on Macs too.

Before:

```
running 30 tests
test bench_add                          ... bench:          12 ns/iter (+/- 2)
test bench_and                          ... bench:         771 ns/iter (+/- 47)
test bench_and_inplace                  ... bench:          16 ns/iter (+/- 2)
test bench_andnot                       ... bench:         794 ns/iter (+/- 358)
test bench_andnot_inplace               ... bench:          15 ns/iter (+/- 3)
test bench_as_slice                     ... bench:          33 ns/iter (+/- 11)
test bench_cardinality_100000           ... bench:           7 ns/iter (+/- 3)
test bench_cardinality_1000000          ... bench:          34 ns/iter (+/- 17)
test bench_contains_false               ... bench:           2 ns/iter (+/- 0)
test bench_contains_true                ... bench:           4 ns/iter (+/- 0)
test bench_create                       ... bench:         539 ns/iter (+/- 334)
test bench_create_with_capacity         ... bench:         430 ns/iter (+/- 244)
test bench_deserialize_100000           ... bench:       1,602 ns/iter (+/- 307)
test bench_deserialize_1000000          ... bench:      11,506 ns/iter (+/- 2,636)
test bench_fast_or                      ... bench:       1,944 ns/iter (+/- 116)
test bench_fast_or_heap                 ... bench:       1,033 ns/iter (+/- 41)
test bench_fast_xor                     ... bench:       1,947 ns/iter (+/- 1,079)
test bench_flip                         ... bench:         735 ns/iter (+/- 38)
test bench_flip_inplace                 ... bench:         173 ns/iter (+/- 43)
test bench_get_serialized_size_in_bytes ... bench:           5 ns/iter (+/- 0)
test bench_is_empty_false               ... bench:           1 ns/iter (+/- 0)
test bench_is_empty_true                ... bench:           1 ns/iter (+/- 0)
test bench_of                           ... bench:         777 ns/iter (+/- 314)
test bench_or                           ... bench:         717 ns/iter (+/- 453)
test bench_or_inplace                   ... bench:         180 ns/iter (+/- 14)
test bench_remove                       ... bench:           2 ns/iter (+/- 1)
test bench_serialize_100000             ... bench:         437 ns/iter (+/- 139)
test bench_serialize_1000000            ... bench:       6,639 ns/iter (+/- 1,975)
test bench_xor                          ... bench:         709 ns/iter (+/- 39)
test bench_xor_inplace                  ... bench:         189 ns/iter (+/- 41)
```

After

```
test bench_add                          ... bench:          12 ns/iter (+/- 4)
test bench_and                          ... bench:         483 ns/iter (+/- 127)
test bench_and_inplace                  ... bench:          16 ns/iter (+/- 4)
test bench_andnot                       ... bench:         507 ns/iter (+/- 194)
test bench_andnot_inplace               ... bench:          15 ns/iter (+/- 4)
test bench_as_slice                     ... bench:          37 ns/iter (+/- 11)
test bench_cardinality_100000           ... bench:           7 ns/iter (+/- 6)
test bench_cardinality_1000000          ... bench:          31 ns/iter (+/- 23)
test bench_contains_false               ... bench:           2 ns/iter (+/- 1)
test bench_contains_true                ... bench:           4 ns/iter (+/- 2)
test bench_create                       ... bench:         165 ns/iter (+/- 71)
test bench_create_with_capacity         ... bench:         127 ns/iter (+/- 34)
test bench_deserialize_100000           ... bench:       1,146 ns/iter (+/- 167)
test bench_deserialize_1000000          ... bench:      11,964 ns/iter (+/- 6,190)
test bench_fast_or                      ... bench:       1,770 ns/iter (+/- 381)
test bench_fast_or_heap                 ... bench:         743 ns/iter (+/- 442)
test bench_fast_xor                     ... bench:       1,750 ns/iter (+/- 389)
test bench_flip                         ... bench:         466 ns/iter (+/- 221)
test bench_flip_inplace                 ... bench:         193 ns/iter (+/- 31)
test bench_get_serialized_size_in_bytes ... bench:           5 ns/iter (+/- 1)
test bench_is_empty_false               ... bench:           1 ns/iter (+/- 1)
test bench_is_empty_true                ... bench:           1 ns/iter (+/- 1)
test bench_of                           ... bench:         532 ns/iter (+/- 111)
test bench_or                           ... bench:         441 ns/iter (+/- 115)
test bench_or_inplace                   ... bench:         228 ns/iter (+/- 55)
test bench_remove                       ... bench:           2 ns/iter (+/- 1)
test bench_serialize_100000             ... bench:         499 ns/iter (+/- 156)
test bench_serialize_1000000            ... bench:       7,088 ns/iter (+/- 2,471)
test bench_xor                          ... bench:         407 ns/iter (+/- 89)
test bench_xor_inplace                  ... bench:         218 ns/iter (+/- 67)
```

Will merge the PR soon.

**Comment by saulius** [comment] 2016-09-10 17:04
@lemire implemented benchmark suite with https://github.com/saulius/croaring-rs/pull/11.

Here is how my results look like on Xeon E5-2680, Centos 7.2:

```
test perf_comp_add_croaring                    ... bench:          81 ns/iter (+/- 5)
test perf_comp_add_rust_roaring                ... bench:          99 ns/iter (+/- 5)
test perf_comp_and_inplace_croaring            ... bench:           5 ns/iter (+/- 0)
test perf_comp_and_inplace_rust_roaring        ... bench:          13 ns/iter (+/- 1)
test perf_comp_and_new_croaring                ... bench:         185 ns/iter (+/- 17)
test perf_comp_and_new_rust_roaring            ... bench:         931 ns/iter (+/- 174)
test perf_comp_cardinality_100000_croaring     ... bench:           5 ns/iter (+/- 0)
test perf_comp_cardinality_100000_rust_roaring ... bench:           1 ns/iter (+/- 0)
test perf_comp_contains_false_croaring         ... bench:           3 ns/iter (+/- 0)
test perf_comp_contains_false_rust_roaring     ... bench:           4 ns/iter (+/- 0)
test perf_comp_contains_true_croaring          ... bench:           5 ns/iter (+/- 0)
test perf_comp_contains_true_rust_roaring      ... bench:           8 ns/iter (+/- 0)
test perf_comp_create_croaring                 ... bench:          40 ns/iter (+/- 1)
test perf_comp_create_rust_roaring             ... bench:           1 ns/iter (+/- 0)
test perf_comp_iter_croaring                   ... bench:      14,848 ns/iter (+/- 97)
test perf_comp_iter_rust_roaring               ... bench:     165,613 ns/iter (+/- 2,284)
test perf_comp_or_inplace_croaring             ... bench:         359 ns/iter (+/- 13)
test perf_comp_or_inplace_rust_roaring         ... bench:       1,817 ns/iter (+/- 536)
test perf_comp_or_new_croaring                 ... bench:         184 ns/iter (+/- 3)
test perf_comp_or_new_rust_roaring             ... bench:       7,712 ns/iter (+/- 50)
test perf_comp_remove_croaring                 ... bench:           5 ns/iter (+/- 0)
test perf_comp_remove_rust_roaring             ... bench:           5 ns/iter (+/- 0)
test perf_comp_xor_inplace_croaring            ... bench:         331 ns/iter (+/- 6)
test perf_comp_xor_inplace_rust_roaring        ... bench:       1,139 ns/iter (+/- 112)
test perf_comp_xor_new_croaring                ... bench:         364 ns/iter (+/- 2)
test perf_comp_xor_new_rust_roaring            ... bench:       4,008 ns/iter (+/- 49)
```

**Comment by lemire** [comment] 2016-09-10 19:26
Excellent. I am not sure benchmarking the time it takes to create an immutable empty set makes sense. At a minimum, add one element to the newly created bitmap. I'll issue a PR for an additional test along this line.

Meanwhile, here are my results under Linux (skylake processor):

```
running 29 tests
test perf_comp_add_croaring                    ... bench:          59 ns/iter (+/- 0)
test perf_comp_add_many_croaring               ... bench:          40 ns/iter (+/- 0)
test perf_comp_add_rust_roaring                ... bench:          72 ns/iter (+/- 0)
test perf_comp_and_inplace_croaring            ... bench:           4 ns/iter (+/- 0)
test perf_comp_and_inplace_rust_roaring        ... bench:          10 ns/iter (+/- 0)
test perf_comp_and_new_croaring                ... bench:         107 ns/iter (+/- 0)
test perf_comp_and_new_rust_roaring            ... bench:         744 ns/iter (+/- 1)
test perf_comp_cardinality_100000_croaring     ... bench:           4 ns/iter (+/- 0)
test perf_comp_cardinality_100000_rust_roaring ... bench:           1 ns/iter (+/- 0)
test perf_comp_contains_false_croaring         ... bench:           2 ns/iter (+/- 0)
test perf_comp_contains_false_rust_roaring     ... bench:           2 ns/iter (+/- 0)
test perf_comp_contains_true_croaring          ... bench:           4 ns/iter (+/- 0)
test perf_comp_contains_true_rust_roaring      ... bench:           5 ns/iter (+/- 0)
test perf_comp_create_and_add_one_croaring     ... bench:          68 ns/iter (+/- 0)
test perf_comp_create_and_add_one_rust_roaring ... bench:          53 ns/iter (+/- 0)
test perf_comp_create_croaring                 ... bench:          28 ns/iter (+/- 0)
test perf_comp_create_rust_roaring             ... bench:           1 ns/iter (+/- 0)
test perf_comp_iter_croaring                   ... bench:       4,570 ns/iter (+/- 3)
test perf_comp_iter_rust_roaring               ... bench:     150,453 ns/iter (+/- 1,052)
test perf_comp_or_inplace_croaring             ... bench:         427 ns/iter (+/- 1)
test perf_comp_or_inplace_rust_roaring         ... bench:       1,283 ns/iter (+/- 10)
test perf_comp_or_new_croaring                 ... bench:         330 ns/iter (+/- 1)
test perf_comp_or_new_rust_roaring             ... bench:       5,746 ns/iter (+/- 4)
test perf_comp_remove_croaring                 ... bench:           4 ns/iter (+/- 0)
test perf_comp_remove_rust_roaring             ... bench:           3 ns/iter (+/- 0)
test perf_comp_xor_inplace_croaring            ... bench:         229 ns/iter (+/- 0)
test perf_comp_xor_inplace_rust_roaring        ... bench:         591 ns/iter (+/- 2)
test perf_comp_xor_new_croaring                ... bench:         216 ns/iter (+/- 0)
test perf_comp_xor_new_rust_roaring            ... bench:       3,118 ns/iter (+/- 7)
```

I think that the tests ``create_and_add_one_croaring`` and ``create_and_add_one_rust_roaring`` are more relevant. 


Note: I would propose you close this issue as you have more than met the demand.

**Comment by saulius** [comment] 2016-09-10 19:50
Sounds good, merged. Lets close this then.

**Closed by saulius** 2016-09-10 19:50 UTC
